#!/usr/bin/env python3
"""Regenerate the role-aware standard-vocabulary manifest from official RDF graphs."""

from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from rdflib import Graph, OWL, RDF, RDFS, URIRef


ROOT = Path(__file__).resolve().parent.parent
LINTER = "https://w3id.org/warsampo-linter#"


@dataclass(frozen=True)
class Vocabulary:
    prefix: str
    namespace: str
    url: str
    rdf_format: str
    sha256: str


VOCABULARIES = (
    Vocabulary(
        "rdf",
        str(RDF),
        "https://www.w3.org/1999/02/22-rdf-syntax-ns.ttl",
        "turtle",
        "93d52b1a5824c7dd6504ca79c16205c0b740a0ba68b7a14952780f52561186a2",
    ),
    Vocabulary(
        "rdfs",
        str(RDFS),
        "https://www.w3.org/2000/01/rdf-schema.ttl",
        "turtle",
        "ecee3a011b7c13ea2a7e40b0a208bfe6be53d69fdd53ee035e09e9f9e5108ad6",
    ),
    Vocabulary(
        "owl",
        str(OWL),
        "https://www.w3.org/2002/07/owl.ttl",
        "turtle",
        "718fa1db7840d3315bfce94398543f91437ef6fe933054fd93f5471d19262fc5",
    ),
    Vocabulary(
        "skos",
        "http://www.w3.org/2004/02/skos/core#",
        "https://www.w3.org/TR/skos-reference/skos.rdf",
        "xml",
        "e79633b8d0564816cee8a99f5c9acf9a0e6fc7257c7209acd684ecad53a89dd6",
    ),
    Vocabulary(
        "dct",
        "http://purl.org/dc/terms/",
        "https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl",
        "turtle",
        "13df401072dd7015bf9d75162f3e41c8138075304b7b9cc1aa1e9c16db976797",
    ),
)


def fetch(vocabulary: Vocabulary) -> bytes:
    request = urllib.request.Request(
        vocabulary.url,
        headers={"User-Agent": "warsampo-linter vocabulary manifest generator"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = response.read()
    actual = hashlib.sha256(payload).hexdigest()
    if actual != vocabulary.sha256:
        raise RuntimeError(
            f"checksum mismatch for {vocabulary.url}: expected {vocabulary.sha256}, got {actual}"
        )
    return payload


def roles(vocabulary: Vocabulary, payload: bytes) -> list[tuple[str, bool, bool]]:
    graph = Graph().parse(data=payload, format=vocabulary.rdf_format)
    result: list[tuple[str, bool, bool]] = []
    for term in sorted(
        {
            subject
            for subject in graph.subjects()
            if isinstance(subject, URIRef) and str(subject).startswith(vocabulary.namespace)
        },
        key=str,
    ):
        term_types = {value for value in graph.objects(term, RDF.type)}
        is_class = RDFS.Class in term_types or OWL.Class in term_types
        is_predicate = RDF.Property in term_types or any(
            isinstance(term_type, URIRef) and str(term_type).endswith("Property")
            for term_type in term_types
        )
        if is_class or is_predicate:
            result.append((str(term), is_class, is_predicate))
    return result


def render() -> str:
    lines = [
        "# Generated by scripts/generate_vocabulary_manifest.py; do not edit by hand.",
        '@prefix dct: <http://purl.org/dc/terms/> .',
        f"@prefix linter: <{LINTER}> .",
        f"@prefix owl: <{OWL}> .",
        f"@prefix rdf: <{RDF}> .",
        f"@prefix rdfs: <{RDFS}> .",
        "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
        "",
        "linter:standardVocabularyManifest",
        "    a linter:VocabularyManifest ;",
        '    dct:modified "2026-08-31" ;',
        "    dct:source",
    ]
    for index, vocabulary in enumerate(VOCABULARIES):
        terminator = " ." if index == len(VOCABULARIES) - 1 else " ,"
        lines.append(f"        <{vocabulary.url}>{terminator}")

    for vocabulary in VOCABULARIES:
        lines.extend(["", f"# {vocabulary.prefix.upper()} terms and their allowed RDF roles."])
        payload = fetch(vocabulary)
        for iri, is_class, is_predicate in roles(vocabulary, payload):
            local_name = iri[len(vocabulary.namespace) :]
            subject = f"{vocabulary.prefix}:{local_name}"
            role_terms = ["linter:knownTerm true"]
            if is_class:
                role_terms.append("linter:classTerm true")
            if is_predicate:
                role_terms.append("linter:predicateTerm true")
            lines.append(f"{subject} " + " ; ".join(role_terms) + " .")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "vocabularies/known-terms.ttl",
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        if arguments.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"outdated vocabulary manifest: {arguments.output}")
        print(f"vocabulary manifest is current: {arguments.output}")
        return
    arguments.output.write_text(generated, encoding="utf-8")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"vocabulary generation failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
